In [1]:
#1. What is a Python library? Why ^o we use Python libraries?
'''
A library is a collection of code that makes everyday tasks more efficient. 
Using Seaborn, for example, you can generate visualisations with just one line of code.
To create a chart from an object, you'd have to write a lot of code without a library like this.
'''

"\nA library is a collection of code that makes everyday tasks more efficient. \nUsing Seaborn, for example, you can generate visualisations with just one line of code.\nTo create a chart from an object, you'd have to write a lot of code without a library like this.\n"

In [ ]:
#2 What is the ^ifference between Numpy array an List?
'''
The main difference is that NumPy arrays are much faster and have strict requirements on the
homogeneity of the objects. For example, a NumPy array of strings can only contain strings and 
no other data types, but a Python list can contain a mixture of strings, numbers, booleans and 
other objects.
'''

In [ ]:
#3 Find the shape, size and dimension of the following array?
'''
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''
'''
shape = 3,4
size = 4*3 = 12
dimensions =  2 - Dimensional.
'''


In [13]:
#4. Write python code to access the first row of the following array?
'''
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''

import numpy as np

arr1 =np.array([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]])

# to read a first row of the array.

arr1[0]

array([1, 2, 3, 4])

In [18]:
#5. How do you access the element at the third row and fourth column from the given numpy array?
'''
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''

arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

# to read 3rd row and fourth column.

arr2[2, 3]

12

In [32]:
#6. Write code to extract all odd-insexed elements from the given numpy array?
'''
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''
arr3 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

# extract all odd-insexed elements.
arr4 = arr3[arr3%2==1] 
arr4

array([ 1,  3,  5,  7,  9, 11])

In [39]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?

arr5 = np.random.randint(0,2,(3,3))
arr5

array([[0, 0, 1],
       [0, 1, 0],
       [0, 0, 1]])

In [52]:
#8. Describe the difference between np.random.rand and np.random.randn?
'''
randn :-  generates samples from the normal distribution, 
while numpy.random.rand from a uniform distribution (in the range [0,1))
'''
arr7 = np.random.randn(10)
print(arr7)

arr6 = np.random.rand(10)
print(arr6)



[ 0.26263838  0.70893344  0.08535132 -0.53840825  0.17778977 -0.55561211
  0.92233828  2.32952739 -0.78880072 -1.2912137 ]
[0.35542841 0.02232084 0.21766421 0.13925286 0.54502517 0.04695605
 0.29384248 0.2037913  0.15333145 0.79648159]


In [65]:
#9. Write code to increase the dimension of the following array?
'''
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''

arr8= np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
arr8.size
# 12

arr8.reshape(2,6)



array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [76]:
#10. How to transpose the following array in NumPy?
'''
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''
arr9 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

arr9.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# 

In [100]:
#11. Consider the following matrix:
'''
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python1
1. Index whiLe multiplication
2. Matix multiplication
3. Add both the maticK
4. Subtact matix B from A 
5.  Diide Matix B by A
'''
a2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
b2 = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])

# 1. Index whiLe multiplication
a2*b2

'''
array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])
'''  

#3. Add both the maticx.
a2 + b2
'''
array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])
'''
# 4. Subtact matix B from A 

a2 - b2
'''
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])
'''

#5.  Diide Matix B by A

a2/b2
'''
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
'''
#2  Matix multiplication.

a2 @ b2
'''
Getting errors because maatrix is not in M * M Format.
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature 
(n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)
'''


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [108]:
#12. Which function in Numpy can be used to swap the byte order of an array?
'''
newbyteorder() Change the byte-ordering of the underlying data, leaving the dtype interpretation as it was.
This is what arr.byteswap() does.
'''
arr9.view(arr9.dtype.newbyteorder())
'''
array([[ 72057594037927936, 144115188075855872, 216172782113783808,
        288230376151711744],
       [360287970189639680, 432345564227567616, 504403158265495552,
        576460752303423488],
       [648518346341351424, 720575940379279360, 792633534417207296,
        864691128455135232]])
'''
arr9.byteswap()
'''
array([[ 72057594037927936, 144115188075855872, 216172782113783808,
        288230376151711744],
       [360287970189639680, 432345564227567616, 504403158265495552,
        576460752303423488],
       [648518346341351424, 720575940379279360, 792633534417207296,
        864691128455135232]])
'''        

array([[ 72057594037927936, 144115188075855872, 216172782113783808,
        288230376151711744],
       [360287970189639680, 432345564227567616, 504403158265495552,
        576460752303423488],
       [648518346341351424, 720575940379279360, 792633534417207296,
        864691128455135232]])

In [ ]:
#13. What is the significance of the np.linalg.inv function?
'''
numpy.linalg.inv() function to calculate the inverse of a matrix. The inverse of a matrix is such that 
if it is multiplied by the original matrix, it results in identity matrix.
'''

In [ ]:
#14. What does the np.reshape function do, and how is it used?
'''
np.reshape function is used to reshape the matrix with in the row and dcolumn. Only thing needs here is 
reshaping of martrix should be always equal to (m * n).
'''


In [ ]:
#15. What is broadcasting in Numpy?
'''
describes how NumPy treats arrays with different shapes during arithmetic operations. 
Subject to certain constraints, the smaller array is “broadcast” across the larger array so that 
they have compatible shapes.
'''
